# Generated by Django 3.1 on 2020-09-04 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('favorite', 'Favorite'), ('unfavorite', 'Unfavorite'), ('review', 'Review')], max_length=200)),
                ('activity', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
