# Generated by Django 3.1 on 2020-08-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0002_auto_20200830_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user_favorite', 'song_favorite')},
        ),
    ]
