# Generated by Django 3.1 on 2020-08-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0002_auto_20200821_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.CharField(help_text='Enter your biography ', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='playtime',
            field=models.CharField(default='0.00', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(default='default.jpeg', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'so bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'so good')]),
        ),
    ]
