# Generated by Django 3.1 on 2020-08-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0002_auto_20200821_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'so bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'so good')]),
        ),
    ]
