# Generated by Django 3.1 on 2020-08-31 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0003_auto_20200830_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default='default.mp3', upload_to='song_directory_path'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='song_favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_favorite', to='myalbums.song'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
