# Generated by Django 3.1 on 2020-08-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0003_auto_20200825_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
