# Generated by Django 3.1 on 2020-08-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/users/avatar.jpg', upload_to='profile_pics'),
        ),
    ]
