# Generated by Django 3.1 on 2020-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0004_auto_20200831_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='thumbnails'),
        ),
    ]
