# Generated by Django 3.1 on 2020-08-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0005_auto_20200825_0938'),
        ('myalbums', '0004_auto_20200825_0601'),
    ]

    operations = [
    ]
