# Generated by Django 3.1 on 2020-08-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0005_auto_20200831_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.FileField(default='default.jpg', upload_to='thumbnails'),
        ),
    ]
