# Generated by Django 3.1 on 2020-08-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myalbums', '0006_merge_20200826_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default='default.mp3', upload_to='song_directory_path'),
        ),
    ]
